// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3V9JGuYbVViVpx2KW7LZdH3mz_OGN_hs',
    appId: '1:833147631416:web:a9b4654680ab12e2aff3cd',
    messagingSenderId: '833147631416',
    projectId: 'fondation-okoukro-app',
    authDomain: 'fondation-okoukro-app.firebaseapp.com',
    storageBucket: 'fondation-okoukro-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3V9JGuYbVViVpx2KW7LZdH3mz_OGN_hs',
    appId: '1:833147631416:android:a9b4654680ab12e2aff3cd',
    messagingSenderId: '833147631416',
    projectId: 'fondation-okoukro-app',
    storageBucket: 'fondation-okoukro-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3V9JGuYbVViVpx2KW7LZdH3mz_OGN_hs',
    appId: '1:833147631416:ios:a9b4654680ab12e2aff3cd',
    messagingSenderId: '833147631416',
    projectId: 'fondation-okoukro-app',
    storageBucket: 'fondation-okoukro-app.firebasestorage.app',
    iosBundleId: 'dev.ekdev.fondationokoukroapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3V9JGuYbVViVpx2KW7LZdH3mz_OGN_hs',
    appId: '1:833147631416:macos:a9b4654680ab12e2aff3cd',
    messagingSenderId: '833147631416',
    projectId: 'fondation-okoukro-app',
    storageBucket: 'fondation-okoukro-app.firebasestorage.app',
    iosBundleId: 'dev.ekdev.fondationokoukroapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3V9JGuYbVViVpx2KW7LZdH3mz_OGN_hs',
    appId: '1:833147631416:windows:a9b4654680ab12e2aff3cd',
    messagingSenderId: '833147631416',
    projectId: 'fondation-okoukro-app',
    authDomain: 'fondation-okoukro-app.firebaseapp.com',
    storageBucket: 'fondation-okoukro-app.firebasestorage.app',
  );
}
